### ISSUE TITLE
Could you please add a license?

### ISSUE THREAD

**Issue by bradishp** [GregorUT/vgchartzScrape#8]
Hi,

I saw the dataset over on Kaggle (https://www.kaggle.com/gregorut/videogamesales) and was hoping to use it for a college project. I wanted to get the most recent copy of the data, so I came here. I would appreciate if you could add a license to this repository (or the dataset on Kaggle if you would prefer) so that I can make use of it. https://choosealicense.com/no-permission/

Thank,
Philip

**Comment by GregorUT** [comment]
This is a screen scrape of data that I do not own.  You would need to contact the owner of VGChartz.com

**Comment by bradishp** [comment]
Thanks for the quick reply. As far as I'm aware (and please correct me if I'm wrong) it is perfecly legal to use public data which has been scrapped. However, it is not legal to use software which doesn't have a license. See https://choosealicense.com/no-permission/ for details

**Comment by bradishp** [comment]
Thank you.
